# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Training configuration
seed: 42
steps: 100000
batch_size: 32
num_workers: 8
log_freq: 100
save_freq: 1000
save_checkpoint: true
resume: false
output_dir: "outputs/train_libero"

# Dataset configuration
dataset:
  repo_id: "jesbu1/libero_test_lerobot_pathmask_rdp_full_path_mask"  # Replace with your LIBERO dataset name

# Policy configuration
policy:
  type: "act"
  device: "cuda"
  use_amp: true
  #pretrained_policy_name_or_path: "jesbu1/act-bridge-v2"
  input_features:
    observation/state:
      type: "STATE"
      shape: [7]  # Padded to match action_dim
    observation/image:
      type: "VISUAL"
      shape: [3, 224, 224]
    observation/wrist_image:
      type: "VISUAL"
      shape: [3, 224, 224]
  output_features:
    actions:
      type: "ACTION"
      shape: [7]

# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 0.0001
  weight_decay: 0.01
  grad_clip_norm: 1.0

# Evaluation configuration
eval_freq: 0
eval:
  n_episodes: 10
  batch_size: 1
  use_async_envs: false

# Wandb configuration
wandb:
  enable: true
  project: "p-masked-vla"
  name: "train_libero_act_debug"
  tags:
    - "act"
    - "libero"
    - "bridge_v2" 