# Training configuration
seed: 42
steps: 1000000
batch_size: 64
num_workers: 16
log_freq: 100
save_freq: 1000
save_checkpoint: true
resume: false
output_dir: "outputs/train_act_bridge"
job_name: "train_act_bridge"

# Dataset configuration
dataset:
  repo_id: "jesbu1/bridge_v2_lerobot"  
  remap_keys: # remaps dataset keys from the original format to the format expected by the policy
    state: "observation.state"
    image: "observation.images.image_0"
    wrist_image: "observation.wrist_image"
    actions: "action"

# Policy configuration
policy:
  type: "act"
  device: "cuda"
  use_amp: true
  input_features:
    state:
      type: "STATE"
      shape: [8]  
    image:
      type: "VISUAL"
      shape: [3, 224, 224]
    wrist_image:
      type: "VISUAL"
      shape: [3, 224, 224]
  output_features:
    action:
      type: "ACTION"
      shape: [7]
  chunk_size: 50
  n_action_steps: 50

# Optimizer configuration
optimizer:
  type: "adamw"
  lr: 0.001
  weight_decay: 0.01
  grad_clip_norm: 1.0

# Evaluation configuration
eval_freq: 0
eval:
  n_episodes: 10
  batch_size: 1
  use_async_envs: false

# Wandb configuration
wandb:
  enable: true
  project: "p-masked-vla"
  run_id: "train_act_libero"